### ISSUE TITLE
Error when compiling rtbkit-deps in ubuntu 14.04

### ISSUE THREAD

**Issue by nguyenxuantuong** [rtbkit/rtbkit#239]
Hi, i follow the instruction from here https://github.com/rtbkit/rtbkit/wiki/RTBkit-Deps-and-Ubuntu-14.04  but get a bunch of error when trying to compile rtbkit in ubuntu 14.04.

Form.cpp:(.text+0x295): undefined reference to `curl_formfree'
/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp/src/curlpp/.libs/libcurlpp.a(Form.o): In function `curlpp::FormParts::File::add(curl_httppost**, curl_httppost**)':
Form.cpp:(.text+0x916): undefined reference to `curl_formadd'
Form.cpp:(.text+0x98b): undefined reference to `curl_formadd'
/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp/src/curlpp/.libs/libcurlpp.a(Form.o): In function `curlpp::FormParts::Content::add(curl_httppost**, curl_httppost**)':
Form.cpp:(.text+0xdf2): undefined reference to `curl_formadd'
Form.cpp:(.text+0xe67): undefined reference to `curl_formadd'

ollect2: error: ld returned 1 exit status
make[2]: *** [example22] Error 1
make[2]: *** [example21] Error 1

/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp/src/curlpp/.libs/libcurlpp.a(cURLpp.o): In function `curlpp::initialize(long)':
cURLpp.cpp:(.text+0x14): undefined reference to `curl_global_init'
/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp/src/curlpp/.libs/libcurlpp.a(cURLpp.o): In function `curlpp::terminate()':
cURLpp.cpp:(.text+0x31): undefined reference to `curl_global_cleanup'
/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp/src/curlpp/.libs/libcurlpp.a(cURLpp.o): In function `curlpp::escape(std::string const&)':
cURLpp.cpp:(.text+0x99): undefined reference to `curl_escape'
cURLpp.cpp:(.text+0x12a): undefined reference to `curl_free'
Form.cpp:(.text+0xdf2): undefined reference to `curl_formadd'
Form.cpp:(.text+0xe67): undefined reference to `curl_formadd'
collect2: error: ld returned 1 exit status
make[2]: *** [example18] Error 1
make[2]: Target `all' not remade because of errors.
make[2]: Leaving directory `/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp/examples'
Making all in doc
make[2]: Entering directory `/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp/doc'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp/doc'
make[2]: Entering directory `/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp'
make[2]: Nothing to be done for `all-am'.
make[2]: Leaving directory `/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp'
make[1]: *** [all-recursive] Error 1
make[1]: Target `all' not remade because of errors.
make[1]: Leaving directory `/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp'
make: *** [install_curlpp] Error 2

can some one enlighten me which can be done to solve the problem? It seems that there is some problem with libcurl? Thanks.

**Comment by mikeburkat** [comment]
Hey it looks like you are missing libcurl, can you try reinstalling libcurl on it's own, and check if there was any errors there. From your rtbkit-deps folder do:

$ make install_libcurl

let me know if you see any errors on libcurl.

**Comment by nguyenxuantuong** [comment]
I was trying to install libcurl again using make install_libcurl. It ran successfully and I can see the library and header in correct folder location. Below are headers and libs inside corresponding folders.

under: /home/ubuntu/local/include/curl/
curl.h  curlbuild.h  curlrules.h  curlver.h  easy.h  mprintf.h  multi.h  stdcheaders.h  typecheck-gcc.h

under: /home/ubuntu/local/lib/
libcurl.a libcurl.la libcurl.so libcurl.so.4 libcurl.so.4.2

But i still got the error when running make all NODEJS_ENABLED=0
Form.cpp:(.text+0x295): undefined reference to `curl_formfree'
/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp/src/curlpp/.libs/libcurlpp.a(Form.o): In function `curlpp::FormParts::File::add(curl_httppost**, curl_httppost**)':
Form.cpp:(.text+0x916): undefined reference to `curl_formadd'
Form.cpp:(.text+0x98b): undefined reference to `curl_formadd'
/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp/src/curlpp/.libs/libcurlpp.a(Form.o): In function `curlpp::FormParts::Content::add(curl_httppost**, curl_httppost**)':
Form.cpp:(.text+0xdf2): undefined reference to `curl_formadd'
Form.cpp:(.text+0xe67): undefined reference to `curl_formadd'
collect2: error: ld returned 1 exit status
make[2]: *** [example20] Error 1
make[2]: Target `all' not remade because of errors.

Leaving directory `/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp/examples'
Making all in doc
make[2]: Entering directory `/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp/doc'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp/doc'
make[2]: Entering directory `/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp'
make[2]: Nothing to be done for `all-am'.
make[2]: Leaving directory `/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp'
make[1]: *** [all-recursive] Error 1
make[1]: Target `all' not remade because of errors.
make[1]: Leaving directory `/home/ubuntu/Documents/workspace/rtbkit-deps/curlpp'
make: *** [install_curlpp] Error 2

Do I have to clean existing build first before running make all again? Thanks.

**Comment by nguyenxuantuong** [comment]
Nvm, seems that a clean install solved the problem.

**Comment by RAttab** [comment]
Alright, then I'll be closing this issue.
