### ISSUE TITLE
Breaking stats server when sending "error reasons

### ISSUE THREAD

**Issue by msempere** [rtbkit/rtbkit#266]
Hi, What is the purpose of sending the error reason to a stats server?

I'm talking about this line:
https://github.com/rtbkit/rtbkit/blob/b67f5c494d8a5ad5660cb750bf7560d6abed353a/rtbkit/core/router/router.cc#L1279

In my side that was braking our server when being hit with reasons like the following:

[bid price 500USD/1M is lower then thebid floor prices 938USD/1M, or are in different currencies USD and USD 0 1446638717 ]

**Comment by mikeburkat** [comment]
this is a bug. that reason comes from [here](https://github.com/rtbkit/rtbkit/blob/6d7df957ec750b992115bfba5281aeeb3b029269/rtbkit/common/exchange_connector.cc#L139)
but that should be a one word reason, not full sentence.
I'll let you know when we push a fix

**Comment by mikeburkat** [comment]
fixed: https://github.com/rtbkit/rtbkit/pull/289
