### ISSUE TITLE
Compiling on a 32 bits system - error thrown by atomic_ops.h

### ISSUE THREAD

**Issue by rcoppola** [rtbkit/rtbkit#281]
Hello !
I'm trying to compile the rtbkit on a 32 bits architecture and failing to do so.
I got an invalid instruction suffix for "inc" error caused by line 119 of the atomic_ops.h file, called when reading data_aliases.cc

FYI I'm working on Ubuntu 14.04.

Do you have any idea of where this problem might come from ?

Thank you,

Ralph.

**Comment by skaag** [comment]
I don't know what the problem is (yet), but just out of curiosity: why are you trying to compile rtbkit on a 32bit system? 😯

**Comment by mikeburkat** [comment]
you can only build rtbkit on a 64bit system.
