### ISSUE TITLE
rtbkit make compile error!

### ISSUE THREAD

**Issue by rodneyqu** [rtbkit/rtbkit#283]
`rtbkit@ip-10-67-173-116:~/rtbkit$ make compile
  [NODEJS_ADDON] libbid_request_node_impl.so
/usr/bin/ld: cannot find -ljs
collect2: ld returned 1 exit status
make: *** [build/x86_64/bin/libbid_request_node_impl.f85de100f3b4cb7113227646b1565104.so] Error 1`

Ubuntu version 12.04
how can i install this lib ?
please tell me, thanks

**Comment by mikeburkat** [comment]
Hi, you can retry, we fixed the bug: https://github.com/rtbkit/rtbkit/commit/5bfa557db6d313f6c27e7cff9c9c58f12711ac5e

**Comment by rodneyqu** [comment]
thank you.
