### ISSUE TITLE
carbon-cache.py start Warning

### ISSUE THREAD

**Issue by rodneyqu** [rtbkit/rtbkit#285]
when i run:

sudo /opt/graphite/bin/carbon-cache.py start

I got the Warning:

/usr/lib/python2.7/dist-packages/zope/__init__.py:3: UserWarning: Module twisted was already imported from /home/rtbkit/.local/lib/python2.7/site-packages/twisted/__init__.pyc, but /opt/graphite/lib is being added to sys.path
  import pkg_resources
Starting carbon-cache (instance a)

Also i find some discussion about this.

https://groups.google.com/a/rtbkit.org/forum/#!topic/discuss/eRZ2gjlMb8I

But it doesn't work for me.

Meanwhile, I can not find the  code 'from twisted.scripts._twistd_unix import daemonize' in file '/opt/graphite/lib/carbon/util.py'. 

So weird

anyone help?

**Comment by jraby** [comment]
Let's discuss configuration issues on the mailing list: https://groups.google.com/a/rtbkit.org/forum/#!topic/discuss/BE45QC_66-E

closing
