### ISSUE TITLE
which  is stable version ？

### ISSUE THREAD

**Issue by rodneyqu** [rtbkit/rtbkit#288]
master is version ==?
where can dowload rtbkit 2.0 version?
thanks

**Comment by mikeburkat** [comment]
master is stable.
as far as versions go we just generally refer to git hashes.

**Comment by rodneyqu** [comment]
thank you for your reply to me.
master is 2.0 version ?
The document said Some modules to 2.0 support http interface.

**Comment by Cipiu** [comment]
Hi,

The rtbkit version 2.0 is not released yet. However the bidders support
http interface (
https://github.com/rtbkit/rtbkit/wiki/How-to-write-a-bidding-agent-using-Python-and-HTTP-API
)
