### ISSUE TITLE
No bid price for go plugin to httpinterface

### ISSUE THREAD

**Issue by robpepper** [rtbkit/rtbkit#295]
Hi,
  I use go to do the bid, but it's not working, the bid price printed out as empty using this package: https://github.com/machinalis/bidderd

 Any idea or suggestions?

Thanks
Rob

**Comment by alep** [comment]
You reported a problem in the wrong project. rtbkit hasn't got anything to do with the bidder agent in that repository. I suggest you open an issue in the right repository https://github.com/machinalis/bidderd/issues and with a bit more detail on what you are doing.

**Comment by robpepper** [comment]
Hi, Ale;
   I moved it to https://github.com/machinalis/bidderd/issues/1

   Now I belong to the right project, what you say?

Rob


ᐧ

**Comment by robpepper** [comment]
Hi Ale,
   Any fix for it?

Thanks,
Tob



ᐧ
