### ISSUE TITLE
ubuntu 14. zookeeper/zookeeper.h: No such file or directory

### ISSUE THREAD

**Issue by dieuit07** [rtbkit/rtbkit#301]
After step ``` cp jml-build/sample.local.mk local.mk ```

I run ``` make compile NODEJS_ENABLED=0 ```  And error missing file appear

```
           [C++] soa/service/zookeeper_configuration_service.cc
In file included from ./soa/service/zookeeper_configuration_service.cc:9:0:
./soa/service/zookeeper.h:9:33: fatal error: zookeeper/zookeeper.h: No such file or directory
 #include <zookeeper/zookeeper.h>
                                 ^
compilation terminated.
```
  
I check file is really not existed in project. which step config I missing?

**Comment by LycenYao** [comment]
Maybe you don't have rtbkit-deps installed in your machine. You will get zookeeper installed after rtbkit-deps installing.

**Comment by dieuit07** [comment]
I allready install that. After install rtbkit-deps. I clone rtbkit inside its folder and continue setup steps. And I try to find file zookeeper/zookeeper.h  in folder of rtbkit-deps, then still not found anywhere

**Comment by LycenYao** [comment]
@dieuit07 This file can be found in your system include directory, such as /usr/local/include, or /usr/include . Maybe you installed rtbkit-deps to a place which is not a usual include directory?

**Comment by dieuit07** [comment]
Yup, you right! I think I missing run ```make``` for rtbkit-deps ( in document not type that, but the main document  rtbkit-deps is exist ). thanks a lot @LycenYao
